export const queryKeys = {
  all: ['fleet'] as const,
  session: ['fleet', 'session'] as const,
  dashboard: ['fleet', 'dashboard'] as const,
  users: ['fleet', 'users'] as const,
  garages: ['fleet', 'garages'] as const,
  clients: ['fleet', 'clients'] as const,
  vehicles: ['fleet', 'vehicles'] as const,
  plates: ['fleet', 'plates'] as const,
  devices: ['fleet', 'devices'] as const,
  cameras: ['fleet', 'cameras'] as const,
  connections: ['fleet', 'connections'] as const,
  recordings: ['fleet', 'recordings'] as const,
  transfers: ['fleet', 'transfers'] as const,
  syncRuns: ['fleet', 'sync-runs'] as const,
  files: ['fleet', 'files'] as const,
  segments: ['fleet', 'segments'] as const,
  processing: ['fleet', 'processing'] as const,
  integrity: ['fleet', 'integrity'] as const,
  audits: ['fleet', 'audits'] as const,
  alerts: ['fleet', 'alerts'] as const,
  storage: ['fleet', 'storage'] as const,
  activity: ['fleet', 'activity'] as const,
  demo: ['fleet', 'demo'] as const,
}
